import Head from "next/head";

const MetaHead = () => {
  return (
    <Head>
        <title>프론트엔드 김영웅 포트폴리오</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}

export default MetaHead